version: "3"
services:
  react-app:
    image: react-app
    stdin_open: true
    ports: 
      - "3000:3000"
    networks:
      - mern-app
  api-server:
    image: api-server
    restart: always
    build: .
    environement: 
          - DB_HOST=json-server
    ports:
      - "4000:4000"
  json-server:
    container_name: json-server-container
    image: json-server-image
    build: ./server
    ports:
      - "3001:3001"
    volumes:
      - ./server/task.json:/data/task.json
command: json-server --watch /data/task.json --host 0.0.0.0
